# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\File\DeskTop\expand\工具箱盒\模拟Explorer\ui\base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ViewFrame = QtWidgets.QFrame(self.centralwidget)
        self.ViewFrame.setGeometry(QtCore.QRect(30, 60, 711, 421))
        self.ViewFrame.setStyleSheet("QFrame#ViewFrame{\n"
"    background-color: #e5e5e5\n"
"}\n"
"QFrame#LVFrame{\n"
"    background-color: #dedede\n"
"}\n"
"QFrame#RVFrame{\n"
"    background-color: #dadada\n"
"}")
        self.ViewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ViewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ViewFrame.setObjectName("ViewFrame")
        self.splitter = QtWidgets.QSplitter(self.ViewFrame)
        self.splitter.setGeometry(QtCore.QRect(20, 20, 671, 371))
        self.splitter.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.LVFrame = QtWidgets.QFrame(self.splitter)
        self.LVFrame.setStyleSheet("")
        self.LVFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LVFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LVFrame.setObjectName("LVFrame")
        self.RVFrame = QtWidgets.QFrame(self.splitter)
        self.RVFrame.setEnabled(True)
        self.RVFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RVFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RVFrame.setObjectName("RVFrame")
        self.AButton = QtWidgets.QPushButton(self.centralwidget)
        self.AButton.setGeometry(QtCore.QRect(340, 10, 112, 34))
        self.AButton.setObjectName("AButton")
        self.ViewFrame.raise_()
        self.label.raise_()
        self.AButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.AButton.clicked.connect(MainWindow.on_AButton_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Explorer"))
        self.AButton.setText(_translate("MainWindow", "PushButton"))
