# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\File\DeskTop\expand\工具箱盒\模拟Explorer\ui\view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1114, 788)
        Form.setStyleSheet("QPushButton[isfiles=true]{\n"
"    text-align: left;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_tree = QtWidgets.QTreeWidget(self.widget)
        self.left_tree.setMinimumSize(QtCore.QSize(300, 0))
        self.left_tree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.left_tree.setObjectName("left_tree")
        self.left_tree.headerItem().setText(0, "1")
        self.horizontalLayout_3.addWidget(self.left_tree)
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.right_scroll = QtWidgets.QScrollArea(self.widget_2)
        self.right_scroll.setWidgetResizable(True)
        self.right_scroll.setObjectName("right_scroll")
        self.right_scroll_widget = QtWidgets.QWidget()
        self.right_scroll_widget.setGeometry(QtCore.QRect(0, 0, 472, 734))
        self.right_scroll_widget.setObjectName("right_scroll_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_scroll_widget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.right_scroll.setWidget(self.right_scroll_widget)
        self.verticalLayout.addWidget(self.right_scroll)
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
